// src/pages/Gallery.tsx
import { Helmet } from "react-helmet-async"
import ImageGallery from "react-image-gallery"

const images = [
	{
		original: "/img/lobby.png",
		thumbnail: "/img/lobby.thumb.png",
		description: "Lobby (By: POMP)",
	},
	{
		original: "/img/IceBear/1.png",
		thumbnail: "/img/IceBear/1.thumb.png",
		description: "Doggos (By: Ice Bear)",
	},
	{
		original: "/img/IceBear/2.png",
		thumbnail: "/img/IceBear/2.thumb.png",
		description: "Bee farm (By: Ice Bear)",
	},
	{
		original: "/img/woww/1.png",
		thumbnail: "/img/woww/1.thumb.png",
		description: "overview (By: woww)",
	},
	{
		original: "/img/IceBear/3.png",
		thumbnail: "/img/IceBear/3.thumb.png",
		description: "Chicken (By: Ice Bear)",
	},
	{
		original: "/img/IceBear/4.png",
		thumbnail: "/img/IceBear/4.thumb.png",
		description: "pp (By: Ice Bear)",
	},
]

function Gallery() {
	return (
		<>
			<Helmet>
				<title>Gallery | LPMC</title>
			</Helmet>
			<h1>Gallery</h1>
			<ImageGallery items={images} />
		</>
	)
}

export default Gallery

// src/views/Gallery.vue
<template>
	<div class="gallery">
		<h1>Gallery</h1>
		<VuePictureSwipe
			:items="[
				{
					src: '/img/lobby.png',
					thumbnail: '/img/lobby.thumb.png',
					w: 3840,
					h: 2160,
					title: 'Lobby (By: POMP)',
				},
				{
					src: '/img/IceBear/1.png',
					thumbnail: '/img/IceBear/1.thumb.png',
					w: 5120,
					h: 2880,
					title: 'Doggos (By: Ice Bear)',
				},
				{
					src: '/img/IceBear/2.png',
					thumbnail: '/img/IceBear/2.thumb.png',
					w: 5120,
					h: 2880,
					title: 'Bee farm (By: Ice Bear)',
				},
				{
					src: '/img/woww/1.png',
					thumbnail: '/img/woww/1.thumb.png',
					w: 5120,
					h: 2880,
					title: 'overview (By: woww)',
				},
				{
					src: '/img/IceBear/3.png',
					thumbnail: '/img/IceBear/3.thumb.png',
					w: 1980,
					h: 1234,
					title: 'Chicken (By: Ice Bear)',
				},
				{
					src: '/img/IceBear/4.png',
					thumbnail: '/img/IceBear/4.thumb.png',
					w: 2486,
					h: 1354,
					title: 'pp (By: Ice Bear)',
				},
			]"
		></VuePictureSwipe>
	</div>
</template>

<script lang="ts">
import VuePictureSwipe from "vue-picture-swipe"

export default {
	components: {
		VuePictureSwipe,
	},
}
</script>

<style lang="scss">
.gallery {
	text-align: center;
	height: 2000px;
}
</style>
