// src/pages/Map.tsx
import { Helmet } from "react-helmet-async"
import styled from "styled-components"

const StyledMapContainer = styled.div`
	width: 100%;
	height: calc(100vh - 80px);
	overflow: hidden;
	background-color: black;
`

const StyledMap = styled.object`
	width: 100%;
	height: 100%;
`

function Map() {
	return (
		<>
			<Helmet>
				<title>Map | LPMC</title>
			</Helmet>
			<StyledMapContainer>
				<StyledMap type="text/html" data="/overview" />
			</StyledMapContainer>
		</>
	)
}

export default Map

// src/views/Map.vue
<template>
	<div class="map">
		<object class="overview" type="text/html" data="/overview"></object>
	</div>
</template>

<script lang="ts">
export default {}
</script>

<style lang="scss">
.map {
	height: calc(100vh - 80px);
	width: 100%;
	background-color: black;
}

.overview {
	height: 100%;
	width: 100%;
}
</style>
